version: '3.5'

services:
  kubernetes-flux-ci-demo:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: kubernetes-flux-ci-demo
    hostname: kubernetes-flux-ci-demo
    volumes:
      - ./:/app
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
    networks:
      - global

networks:
  global:
    name: global
    external: true